export interface Pet {
  /**
   * Id of pet, is generated by db
   */
  _id: string;

  /**
   * Name of pet, i.e "Bob the dog"
   */
  name: string;

  /**
   * Age in years
   */
  age: number;

  /**
   * Date when pet was created
   */
  created: Date;
}
